apiVersion: v2
appVersion: 0.0.1-rc.20251212234216.ae715e4
description: Information about the architecture and makeup of the LTC's server infrastructure.
home: https://heme-analyzer-app.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: heme-analyzer-app
sources:
  - https://github.com/bcit-ltc/
  - https://github.com/bcit-ltc/heme-analyzer-app
version: 0.0.1-rc.20251212234216.ae715e4
dependencies:
  - name: apps-common
    version: ">=0.3.4"
    repository: https://bcit-ltc.github.io/helm-charts
