apiVersion: v2
appVersion: 1.0.3
description: Content delivery and proxy service for static assets and third-party API routing.
home: https://common.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: common
sources:
  - https://github.com/bcit-ltc/
  - https://github.com/bcit-ltc/common
version: 1.0.3
dependencies:
  - name: apps-common
    version: ">=0.3.0"
    repository: https://bcit-ltc.github.io/helm-charts
