apiVersion: v2
appVersion: 1.1.6-rc.20260206193819.bdda9d4
description: A reference for anyone preparing Word documents to be converted into HTML.
home: https://conversion-guide.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: conversion-guide
sources:
  - https://github.com/bcit-ltc/
  - https://github.com/bcit-ltc/conversion-guide
version: 1.1.6-rc.20260206193819.bdda9d4
dependencies:
  - name: apps-common
    version: ">=0.3.4"
    repository: https://bcit-ltc.github.io/helm-charts
