apiVersion: v2
appVersion: 1.0.1-rc.20251107055825.6ca81ef
description: Frontend of the Qcon service. Requires the qcon-api processor engine to work correctly.
home: https://qcon-web.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: qcon-web
sources:
  - https://github.com/bcit-ltc/
  - https://github.com/bcit-ltc/qcon-web
version: 1.0.1-rc.20251107055825.6ca81ef
dependencies:
  - name: apps-common
    version: ">=0.3.0"
    repository: https://bcit-ltc.github.io/helm-charts
