apiVersion: v2
appVersion: 1.0.5-rc.20251203203418.858628b
description: legacy-soh-3dbirth is a legacy multimedia application.
home: https://legacy-soh-3dbirth.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: legacy-soh-3dbirth
sources:
  - https://github.com/bcit-ltc/
  - https://github.com/bcit-ltc/legacy-html
version: 1.0.5-rc.20251203203418.858628b
dependencies:
  - name: apps-common
    version: ">=0.3.0"
    repository: https://bcit-ltc.github.io/helm-charts
