apiVersion: v2
name: apps-common
description: Common helpers and partials for LTC Helm charts (library chart).
type: library
version: 0.3.5
appVersion: 0.3.5
icon: https://course-production.ltc.bcit.ca/favicon.ico
keywords:
  - library
  - helpers
  - common
