apiVersion: v2
appVersion: 1.1.4-rc.20251114065904.f28c4ff
description: Sugar-Suite is a "Framework Factory" used to produce customized stylesheets designed for building online courses in HTML.
home: https://sugar-suite.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: sugar-suite
sources:
  - https://github.com/bcit-ltc/
  - https://github.com/bcit-ltc/sugar-suite
version: 1.1.4-rc.20251114065904.f28c4ff
dependencies:
  - name: apps-common
    version: ">=0.3.0"
    repository: https://bcit-ltc.github.io/helm-charts
