apiVersion: v2
appVersion: 1.1.2-rc.20251211071702.f535a6a
description: Information about how to use [Qcon](https://qcon.ltc.bcit.ca).
home: https://qcon-guide.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: qcon-guide
sources:
  - https://github.com/bcit-ltc/
  - https://github.com/bcit-ltc/qcon-guide
version: 1.1.2-rc.20251211071702.f535a6a
dependencies:
  - name: apps-common
    version: ">=0.3.4"
    repository: https://bcit-ltc.github.io/helm-charts
