apiVersion: v2
appVersion: 1.0.1
description: legacy-soc-royaloak is a legacy multimedia application.
home: https://legacy-soc-royaloak.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: legacy-soc-royaloak
sources:
  - https://github.com/bcit-ltc/
  - https://github.com/bcit-ltc/legacy-soc-royaloak
version: 1.0.1
dependencies:
  - name: apps-common
    version: ">=0.3.4"
    repository: https://bcit-ltc.github.io/helm-charts
