apiVersion: v2
appVersion: 1.1.4
description: legacy-html is a legacy multimedia application.
home: https://legacy-html.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: legacy-html
sources:
  - https://github.com/bcit-ltc/
  - https://github.com/bcit-ltc/legacy-html
version: 1.1.4
dependencies:
  - name: apps-common
    version: ">=0.3.4"
    repository: https://bcit-ltc.github.io/helm-charts
