apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "haproxy-operator.rbacName" . }}
  labels:
{{ include "apps-common.app.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "haproxy-operator.rbacName" . }}
  labels:
{{ include "apps-common.app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "haproxy-operator.rbacName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "haproxy-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
