apiVersion: v2
name: haproxy-operator
description: Minimal K8S Operator that configures HAProxy using the Dataplane API
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: apps-common
    version: ">=0.3.4"
    repository: https://bcit-ltc.github.io/helm-charts
