apiVersion: v2
appVersion: 1.0.2-rc.20251210212721.01ad845
description: legacy-socas is a legacy multimedia application.
home: https://legacy-socas.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: legacy-socas
sources:
  - https://github.com/bcit-ltc/
  - https://github.com/bcit-ltc/legacy-socas
version: 1.0.2-rc.20251210212721.01ad845
dependencies:
  - name: apps-common
    version: ">=0.3.4"
    repository: https://bcit-ltc.github.io/helm-charts
