apiVersion: v2
appVersion: 2.0.1
description: Backend API for the Qcon application. It provides a websocket endpoint for converting documents from word to SCORM format.
home: https://scheduler-api.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: scheduler-api
sources:
  - https://github.com/bcit-ltc/
  - https://github.com/bcit-ltc/scheduler-api
version: 2.0.1
dependencies:
  - name: apps-common
    version: ">=0.3.4"
    repository: https://bcit-ltc.github.io/helm-charts
